# Generated by Django 4.2.5 on 2023-09-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_specification_specification_specificationtext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specification',
            old_name='specificationText',
            new_name='specification',
        ),
    ]
