# Generated by Django 4.2.5 on 2023-09-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_rename_specificationtext_specification_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(unique=True, upload_to='produtos/'),
        ),
    ]
