# Generated by Django 4.2.5 on 2023-09-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(unique=True, upload_to='produtos/principal/'),
        ),
    ]
